services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: ch15-split-exercise:dev
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      XDEBUG_MODE: debug,develop
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
    extra_hosts:
      - "host.docker.internal:host-gateway"
