FROM php:8.3-cli-bookworm
WORKDIR /app
COPY . .
RUN apt-get update \
 && apt-get install -y --no-install-recommends git unzip \
 && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
 && composer install --no-dev --no-interaction --no-ansi
