FROM golang:1.22-bookworm AS build
WORKDIR /src
COPY main.go .
RUN CGO_ENABLED=0 go build -o /out/hello main.go

FROM gcr.io/distroless/static-debian12
COPY --from=build /out/hello /hello
ENTRYPOINT ["/hello"]
