name: ch11-tls-edge

services:
  web:
    image: nginx:stable-alpine
    ports:
      - "127.0.0.1:${HTTP_PORT:-8080}:80"
      - "127.0.0.1:${HTTPS_PORT:-8443}:443"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/certs:/etc/nginx/certs:ro
      - ./public:/var/www/html/public:ro
    depends_on:
      - app

  app:
    image: php:8.3-fpm-bookworm
    expose:
      - "9000"
    volumes:
      - ./public:/var/www/html/public:ro
